"""add cng_shift_readings and tank_readings

Revision ID: 2fc50a7d52a6
Revises: 8de07e1ef1bd
Create Date: 2026-05-15 16:38:02.733094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc50a7d52a6'
down_revision = '8de07e1ef1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
