"""Add DB-backed users, lube_products, lube_transactions, expenses, fleet_card_transactions; update payments_received

Revision ID: 8de07e1ef1bd
Revises: 59b2a8a6efbf
Create Date: 2026-05-07 11:25:29.863530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de07e1ef1bd'
down_revision = '59b2a8a6efbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments_received', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True, server_default='confirmed'))
        batch_op.add_column(sa.Column('verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_payments_received_verified_by_users', 'users', ['verified_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments_received', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_received_verified_by_users', type_='foreignkey')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verified_by')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
